name = "ShowCode"
uuid = "c14aca87-bccd-473b-bf6f-1f278cb6ee85"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LLVM_jll = "86de99a1-58d6-5da7-8064-bd56ce2e322c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
